/*
 * Auto-generated file. Created by MyBatis Generator
 */
package com.attendance.api.infrastructure.database.mapper

import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.attendaceId
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay1
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay10
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay11
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay12
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay13
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay14
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay15
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay16
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay17
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay18
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay19
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay2
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay20
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay21
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay22
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay23
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay24
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay25
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay26
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay27
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay28
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay29
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay3
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay30
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay31
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay4
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay5
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay6
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay7
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay8
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.breakTimeDay9
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay1
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay10
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay11
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay12
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay13
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay14
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay15
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay16
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay17
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay18
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay19
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay2
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay20
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay21
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay22
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay23
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay24
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay25
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay26
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay27
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay28
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay29
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay3
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay30
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay31
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay4
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay5
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay6
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay7
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay8
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.endTimeDay9
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.month
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay1
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay10
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay11
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay12
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay13
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay14
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay15
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay16
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay17
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay18
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay19
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay2
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay20
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay21
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay22
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay23
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay24
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay25
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay26
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay27
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay28
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay29
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay3
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay30
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay31
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay4
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay5
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay6
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay7
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay8
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.startTimeDay9
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.userId
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle1
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle10
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle11
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle12
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle13
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle14
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle15
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle16
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle17
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle18
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle19
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle2
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle20
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle21
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle22
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle23
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle24
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle25
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle26
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle27
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle28
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle29
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle3
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle30
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle31
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle4
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle5
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle6
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle7
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle8
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.workStyle9
import com.attendance.api.infrastructure.database.mapper.AttendanceBasicInfoDynamicSqlSupport.AttendanceBasicInfo.year
import com.attendance.api.infrastructure.database.record.AttendanceBasicInfoRecord
import org.mybatis.dynamic.sql.SqlBuilder.isEqualTo
import org.mybatis.dynamic.sql.util.kotlin.*
import org.mybatis.dynamic.sql.util.kotlin.mybatis3.*

fun AttendanceBasicInfoMapper.count(completer: CountCompleter) =
    countFrom(this::count, AttendanceBasicInfo, completer)

fun AttendanceBasicInfoMapper.delete(completer: DeleteCompleter) =
    deleteFrom(this::delete, AttendanceBasicInfo, completer)

fun AttendanceBasicInfoMapper.deleteByPrimaryKey(attendaceId_: Int) =
    delete {
        where(attendaceId, isEqualTo(attendaceId_))
    }

fun AttendanceBasicInfoMapper.insert(record: AttendanceBasicInfoRecord) =
    insert(this::insert, record, AttendanceBasicInfo) {
        map(attendaceId).toProperty("attendaceId")
        map(userId).toProperty("userId")
        map(year).toProperty("year")
        map(month).toProperty("month")
        map(workStyle1).toProperty("workStyle1")
        map(startTimeDay1).toProperty("startTimeDay1")
        map(endTimeDay1).toProperty("endTimeDay1")
        map(breakTimeDay1).toProperty("breakTimeDay1")
        map(workStyle2).toProperty("workStyle2")
        map(startTimeDay2).toProperty("startTimeDay2")
        map(endTimeDay2).toProperty("endTimeDay2")
        map(breakTimeDay2).toProperty("breakTimeDay2")
        map(workStyle3).toProperty("workStyle3")
        map(startTimeDay3).toProperty("startTimeDay3")
        map(endTimeDay3).toProperty("endTimeDay3")
        map(breakTimeDay3).toProperty("breakTimeDay3")
        map(workStyle4).toProperty("workStyle4")
        map(startTimeDay4).toProperty("startTimeDay4")
        map(endTimeDay4).toProperty("endTimeDay4")
        map(breakTimeDay4).toProperty("breakTimeDay4")
        map(workStyle5).toProperty("workStyle5")
        map(startTimeDay5).toProperty("startTimeDay5")
        map(endTimeDay5).toProperty("endTimeDay5")
        map(breakTimeDay5).toProperty("breakTimeDay5")
        map(workStyle6).toProperty("workStyle6")
        map(startTimeDay6).toProperty("startTimeDay6")
        map(endTimeDay6).toProperty("endTimeDay6")
        map(breakTimeDay6).toProperty("breakTimeDay6")
        map(workStyle7).toProperty("workStyle7")
        map(startTimeDay7).toProperty("startTimeDay7")
        map(endTimeDay7).toProperty("endTimeDay7")
        map(breakTimeDay7).toProperty("breakTimeDay7")
        map(workStyle8).toProperty("workStyle8")
        map(startTimeDay8).toProperty("startTimeDay8")
        map(endTimeDay8).toProperty("endTimeDay8")
        map(breakTimeDay8).toProperty("breakTimeDay8")
        map(workStyle9).toProperty("workStyle9")
        map(startTimeDay9).toProperty("startTimeDay9")
        map(endTimeDay9).toProperty("endTimeDay9")
        map(breakTimeDay9).toProperty("breakTimeDay9")
        map(workStyle10).toProperty("workStyle10")
        map(startTimeDay10).toProperty("startTimeDay10")
        map(endTimeDay10).toProperty("endTimeDay10")
        map(breakTimeDay10).toProperty("breakTimeDay10")
        map(workStyle11).toProperty("workStyle11")
        map(startTimeDay11).toProperty("startTimeDay11")
        map(endTimeDay11).toProperty("endTimeDay11")
        map(breakTimeDay11).toProperty("breakTimeDay11")
        map(workStyle12).toProperty("workStyle12")
        map(startTimeDay12).toProperty("startTimeDay12")
        map(endTimeDay12).toProperty("endTimeDay12")
        map(breakTimeDay12).toProperty("breakTimeDay12")
        map(workStyle13).toProperty("workStyle13")
        map(startTimeDay13).toProperty("startTimeDay13")
        map(endTimeDay13).toProperty("endTimeDay13")
        map(breakTimeDay13).toProperty("breakTimeDay13")
        map(workStyle14).toProperty("workStyle14")
        map(startTimeDay14).toProperty("startTimeDay14")
        map(endTimeDay14).toProperty("endTimeDay14")
        map(breakTimeDay14).toProperty("breakTimeDay14")
        map(workStyle15).toProperty("workStyle15")
        map(startTimeDay15).toProperty("startTimeDay15")
        map(endTimeDay15).toProperty("endTimeDay15")
        map(breakTimeDay15).toProperty("breakTimeDay15")
        map(workStyle16).toProperty("workStyle16")
        map(startTimeDay16).toProperty("startTimeDay16")
        map(endTimeDay16).toProperty("endTimeDay16")
        map(breakTimeDay16).toProperty("breakTimeDay16")
        map(workStyle17).toProperty("workStyle17")
        map(startTimeDay17).toProperty("startTimeDay17")
        map(endTimeDay17).toProperty("endTimeDay17")
        map(breakTimeDay17).toProperty("breakTimeDay17")
        map(workStyle18).toProperty("workStyle18")
        map(startTimeDay18).toProperty("startTimeDay18")
        map(endTimeDay18).toProperty("endTimeDay18")
        map(breakTimeDay18).toProperty("breakTimeDay18")
        map(workStyle19).toProperty("workStyle19")
        map(startTimeDay19).toProperty("startTimeDay19")
        map(endTimeDay19).toProperty("endTimeDay19")
        map(breakTimeDay19).toProperty("breakTimeDay19")
        map(workStyle20).toProperty("workStyle20")
        map(startTimeDay20).toProperty("startTimeDay20")
        map(endTimeDay20).toProperty("endTimeDay20")
        map(breakTimeDay20).toProperty("breakTimeDay20")
        map(workStyle21).toProperty("workStyle21")
        map(startTimeDay21).toProperty("startTimeDay21")
        map(endTimeDay21).toProperty("endTimeDay21")
        map(breakTimeDay21).toProperty("breakTimeDay21")
        map(workStyle22).toProperty("workStyle22")
        map(startTimeDay22).toProperty("startTimeDay22")
        map(endTimeDay22).toProperty("endTimeDay22")
        map(breakTimeDay22).toProperty("breakTimeDay22")
        map(workStyle23).toProperty("workStyle23")
        map(startTimeDay23).toProperty("startTimeDay23")
        map(endTimeDay23).toProperty("endTimeDay23")
        map(breakTimeDay23).toProperty("breakTimeDay23")
        map(workStyle24).toProperty("workStyle24")
        map(startTimeDay24).toProperty("startTimeDay24")
        map(endTimeDay24).toProperty("endTimeDay24")
        map(breakTimeDay24).toProperty("breakTimeDay24")
        map(workStyle25).toProperty("workStyle25")
        map(startTimeDay25).toProperty("startTimeDay25")
        map(endTimeDay25).toProperty("endTimeDay25")
        map(breakTimeDay25).toProperty("breakTimeDay25")
        map(workStyle26).toProperty("workStyle26")
        map(startTimeDay26).toProperty("startTimeDay26")
        map(endTimeDay26).toProperty("endTimeDay26")
        map(breakTimeDay26).toProperty("breakTimeDay26")
        map(workStyle27).toProperty("workStyle27")
        map(startTimeDay27).toProperty("startTimeDay27")
        map(endTimeDay27).toProperty("endTimeDay27")
        map(breakTimeDay27).toProperty("breakTimeDay27")
        map(workStyle28).toProperty("workStyle28")
        map(startTimeDay28).toProperty("startTimeDay28")
        map(endTimeDay28).toProperty("endTimeDay28")
        map(breakTimeDay28).toProperty("breakTimeDay28")
        map(workStyle29).toProperty("workStyle29")
        map(startTimeDay29).toProperty("startTimeDay29")
        map(endTimeDay29).toProperty("endTimeDay29")
        map(breakTimeDay29).toProperty("breakTimeDay29")
        map(workStyle30).toProperty("workStyle30")
        map(startTimeDay30).toProperty("startTimeDay30")
        map(endTimeDay30).toProperty("endTimeDay30")
        map(breakTimeDay30).toProperty("breakTimeDay30")
        map(workStyle31).toProperty("workStyle31")
        map(startTimeDay31).toProperty("startTimeDay31")
        map(endTimeDay31).toProperty("endTimeDay31")
        map(breakTimeDay31).toProperty("breakTimeDay31")
    }

fun AttendanceBasicInfoMapper.insertMultiple(records: Collection<AttendanceBasicInfoRecord>) =
    insertMultiple(this::insertMultiple, records, AttendanceBasicInfo) {
        map(attendaceId).toProperty("attendaceId")
        map(userId).toProperty("userId")
        map(year).toProperty("year")
        map(month).toProperty("month")
        map(workStyle1).toProperty("workStyle1")
        map(startTimeDay1).toProperty("startTimeDay1")
        map(endTimeDay1).toProperty("endTimeDay1")
        map(breakTimeDay1).toProperty("breakTimeDay1")
        map(workStyle2).toProperty("workStyle2")
        map(startTimeDay2).toProperty("startTimeDay2")
        map(endTimeDay2).toProperty("endTimeDay2")
        map(breakTimeDay2).toProperty("breakTimeDay2")
        map(workStyle3).toProperty("workStyle3")
        map(startTimeDay3).toProperty("startTimeDay3")
        map(endTimeDay3).toProperty("endTimeDay3")
        map(breakTimeDay3).toProperty("breakTimeDay3")
        map(workStyle4).toProperty("workStyle4")
        map(startTimeDay4).toProperty("startTimeDay4")
        map(endTimeDay4).toProperty("endTimeDay4")
        map(breakTimeDay4).toProperty("breakTimeDay4")
        map(workStyle5).toProperty("workStyle5")
        map(startTimeDay5).toProperty("startTimeDay5")
        map(endTimeDay5).toProperty("endTimeDay5")
        map(breakTimeDay5).toProperty("breakTimeDay5")
        map(workStyle6).toProperty("workStyle6")
        map(startTimeDay6).toProperty("startTimeDay6")
        map(endTimeDay6).toProperty("endTimeDay6")
        map(breakTimeDay6).toProperty("breakTimeDay6")
        map(workStyle7).toProperty("workStyle7")
        map(startTimeDay7).toProperty("startTimeDay7")
        map(endTimeDay7).toProperty("endTimeDay7")
        map(breakTimeDay7).toProperty("breakTimeDay7")
        map(workStyle8).toProperty("workStyle8")
        map(startTimeDay8).toProperty("startTimeDay8")
        map(endTimeDay8).toProperty("endTimeDay8")
        map(breakTimeDay8).toProperty("breakTimeDay8")
        map(workStyle9).toProperty("workStyle9")
        map(startTimeDay9).toProperty("startTimeDay9")
        map(endTimeDay9).toProperty("endTimeDay9")
        map(breakTimeDay9).toProperty("breakTimeDay9")
        map(workStyle10).toProperty("workStyle10")
        map(startTimeDay10).toProperty("startTimeDay10")
        map(endTimeDay10).toProperty("endTimeDay10")
        map(breakTimeDay10).toProperty("breakTimeDay10")
        map(workStyle11).toProperty("workStyle11")
        map(startTimeDay11).toProperty("startTimeDay11")
        map(endTimeDay11).toProperty("endTimeDay11")
        map(breakTimeDay11).toProperty("breakTimeDay11")
        map(workStyle12).toProperty("workStyle12")
        map(startTimeDay12).toProperty("startTimeDay12")
        map(endTimeDay12).toProperty("endTimeDay12")
        map(breakTimeDay12).toProperty("breakTimeDay12")
        map(workStyle13).toProperty("workStyle13")
        map(startTimeDay13).toProperty("startTimeDay13")
        map(endTimeDay13).toProperty("endTimeDay13")
        map(breakTimeDay13).toProperty("breakTimeDay13")
        map(workStyle14).toProperty("workStyle14")
        map(startTimeDay14).toProperty("startTimeDay14")
        map(endTimeDay14).toProperty("endTimeDay14")
        map(breakTimeDay14).toProperty("breakTimeDay14")
        map(workStyle15).toProperty("workStyle15")
        map(startTimeDay15).toProperty("startTimeDay15")
        map(endTimeDay15).toProperty("endTimeDay15")
        map(breakTimeDay15).toProperty("breakTimeDay15")
        map(workStyle16).toProperty("workStyle16")
        map(startTimeDay16).toProperty("startTimeDay16")
        map(endTimeDay16).toProperty("endTimeDay16")
        map(breakTimeDay16).toProperty("breakTimeDay16")
        map(workStyle17).toProperty("workStyle17")
        map(startTimeDay17).toProperty("startTimeDay17")
        map(endTimeDay17).toProperty("endTimeDay17")
        map(breakTimeDay17).toProperty("breakTimeDay17")
        map(workStyle18).toProperty("workStyle18")
        map(startTimeDay18).toProperty("startTimeDay18")
        map(endTimeDay18).toProperty("endTimeDay18")
        map(breakTimeDay18).toProperty("breakTimeDay18")
        map(workStyle19).toProperty("workStyle19")
        map(startTimeDay19).toProperty("startTimeDay19")
        map(endTimeDay19).toProperty("endTimeDay19")
        map(breakTimeDay19).toProperty("breakTimeDay19")
        map(workStyle20).toProperty("workStyle20")
        map(startTimeDay20).toProperty("startTimeDay20")
        map(endTimeDay20).toProperty("endTimeDay20")
        map(breakTimeDay20).toProperty("breakTimeDay20")
        map(workStyle21).toProperty("workStyle21")
        map(startTimeDay21).toProperty("startTimeDay21")
        map(endTimeDay21).toProperty("endTimeDay21")
        map(breakTimeDay21).toProperty("breakTimeDay21")
        map(workStyle22).toProperty("workStyle22")
        map(startTimeDay22).toProperty("startTimeDay22")
        map(endTimeDay22).toProperty("endTimeDay22")
        map(breakTimeDay22).toProperty("breakTimeDay22")
        map(workStyle23).toProperty("workStyle23")
        map(startTimeDay23).toProperty("startTimeDay23")
        map(endTimeDay23).toProperty("endTimeDay23")
        map(breakTimeDay23).toProperty("breakTimeDay23")
        map(workStyle24).toProperty("workStyle24")
        map(startTimeDay24).toProperty("startTimeDay24")
        map(endTimeDay24).toProperty("endTimeDay24")
        map(breakTimeDay24).toProperty("breakTimeDay24")
        map(workStyle25).toProperty("workStyle25")
        map(startTimeDay25).toProperty("startTimeDay25")
        map(endTimeDay25).toProperty("endTimeDay25")
        map(breakTimeDay25).toProperty("breakTimeDay25")
        map(workStyle26).toProperty("workStyle26")
        map(startTimeDay26).toProperty("startTimeDay26")
        map(endTimeDay26).toProperty("endTimeDay26")
        map(breakTimeDay26).toProperty("breakTimeDay26")
        map(workStyle27).toProperty("workStyle27")
        map(startTimeDay27).toProperty("startTimeDay27")
        map(endTimeDay27).toProperty("endTimeDay27")
        map(breakTimeDay27).toProperty("breakTimeDay27")
        map(workStyle28).toProperty("workStyle28")
        map(startTimeDay28).toProperty("startTimeDay28")
        map(endTimeDay28).toProperty("endTimeDay28")
        map(breakTimeDay28).toProperty("breakTimeDay28")
        map(workStyle29).toProperty("workStyle29")
        map(startTimeDay29).toProperty("startTimeDay29")
        map(endTimeDay29).toProperty("endTimeDay29")
        map(breakTimeDay29).toProperty("breakTimeDay29")
        map(workStyle30).toProperty("workStyle30")
        map(startTimeDay30).toProperty("startTimeDay30")
        map(endTimeDay30).toProperty("endTimeDay30")
        map(breakTimeDay30).toProperty("breakTimeDay30")
        map(workStyle31).toProperty("workStyle31")
        map(startTimeDay31).toProperty("startTimeDay31")
        map(endTimeDay31).toProperty("endTimeDay31")
        map(breakTimeDay31).toProperty("breakTimeDay31")
    }

fun AttendanceBasicInfoMapper.insertMultiple(vararg records: AttendanceBasicInfoRecord) =
    insertMultiple(records.toList())

fun AttendanceBasicInfoMapper.insertSelective(record: AttendanceBasicInfoRecord) =
    insert(this::insert, record, AttendanceBasicInfo) {
        map(attendaceId).toPropertyWhenPresent("attendaceId", record::attendaceId)
        map(userId).toPropertyWhenPresent("userId", record::userId)
        map(year).toPropertyWhenPresent("year", record::year)
        map(month).toPropertyWhenPresent("month", record::month)
        map(workStyle1).toPropertyWhenPresent("workStyle1", record::workStyle1)
        map(startTimeDay1).toPropertyWhenPresent("startTimeDay1", record::startTimeDay1)
        map(endTimeDay1).toPropertyWhenPresent("endTimeDay1", record::endTimeDay1)
        map(breakTimeDay1).toPropertyWhenPresent("breakTimeDay1", record::breakTimeDay1)
        map(workStyle2).toPropertyWhenPresent("workStyle2", record::workStyle2)
        map(startTimeDay2).toPropertyWhenPresent("startTimeDay2", record::startTimeDay2)
        map(endTimeDay2).toPropertyWhenPresent("endTimeDay2", record::endTimeDay2)
        map(breakTimeDay2).toPropertyWhenPresent("breakTimeDay2", record::breakTimeDay2)
        map(workStyle3).toPropertyWhenPresent("workStyle3", record::workStyle3)
        map(startTimeDay3).toPropertyWhenPresent("startTimeDay3", record::startTimeDay3)
        map(endTimeDay3).toPropertyWhenPresent("endTimeDay3", record::endTimeDay3)
        map(breakTimeDay3).toPropertyWhenPresent("breakTimeDay3", record::breakTimeDay3)
        map(workStyle4).toPropertyWhenPresent("workStyle4", record::workStyle4)
        map(startTimeDay4).toPropertyWhenPresent("startTimeDay4", record::startTimeDay4)
        map(endTimeDay4).toPropertyWhenPresent("endTimeDay4", record::endTimeDay4)
        map(breakTimeDay4).toPropertyWhenPresent("breakTimeDay4", record::breakTimeDay4)
        map(workStyle5).toPropertyWhenPresent("workStyle5", record::workStyle5)
        map(startTimeDay5).toPropertyWhenPresent("startTimeDay5", record::startTimeDay5)
        map(endTimeDay5).toPropertyWhenPresent("endTimeDay5", record::endTimeDay5)
        map(breakTimeDay5).toPropertyWhenPresent("breakTimeDay5", record::breakTimeDay5)
        map(workStyle6).toPropertyWhenPresent("workStyle6", record::workStyle6)
        map(startTimeDay6).toPropertyWhenPresent("startTimeDay6", record::startTimeDay6)
        map(endTimeDay6).toPropertyWhenPresent("endTimeDay6", record::endTimeDay6)
        map(breakTimeDay6).toPropertyWhenPresent("breakTimeDay6", record::breakTimeDay6)
        map(workStyle7).toPropertyWhenPresent("workStyle7", record::workStyle7)
        map(startTimeDay7).toPropertyWhenPresent("startTimeDay7", record::startTimeDay7)
        map(endTimeDay7).toPropertyWhenPresent("endTimeDay7", record::endTimeDay7)
        map(breakTimeDay7).toPropertyWhenPresent("breakTimeDay7", record::breakTimeDay7)
        map(workStyle8).toPropertyWhenPresent("workStyle8", record::workStyle8)
        map(startTimeDay8).toPropertyWhenPresent("startTimeDay8", record::startTimeDay8)
        map(endTimeDay8).toPropertyWhenPresent("endTimeDay8", record::endTimeDay8)
        map(breakTimeDay8).toPropertyWhenPresent("breakTimeDay8", record::breakTimeDay8)
        map(workStyle9).toPropertyWhenPresent("workStyle9", record::workStyle9)
        map(startTimeDay9).toPropertyWhenPresent("startTimeDay9", record::startTimeDay9)
        map(endTimeDay9).toPropertyWhenPresent("endTimeDay9", record::endTimeDay9)
        map(breakTimeDay9).toPropertyWhenPresent("breakTimeDay9", record::breakTimeDay9)
        map(workStyle10).toPropertyWhenPresent("workStyle10", record::workStyle10)
        map(startTimeDay10).toPropertyWhenPresent("startTimeDay10", record::startTimeDay10)
        map(endTimeDay10).toPropertyWhenPresent("endTimeDay10", record::endTimeDay10)
        map(breakTimeDay10).toPropertyWhenPresent("breakTimeDay10", record::breakTimeDay10)
        map(workStyle11).toPropertyWhenPresent("workStyle11", record::workStyle11)
        map(startTimeDay11).toPropertyWhenPresent("startTimeDay11", record::startTimeDay11)
        map(endTimeDay11).toPropertyWhenPresent("endTimeDay11", record::endTimeDay11)
        map(breakTimeDay11).toPropertyWhenPresent("breakTimeDay11", record::breakTimeDay11)
        map(workStyle12).toPropertyWhenPresent("workStyle12", record::workStyle12)
        map(startTimeDay12).toPropertyWhenPresent("startTimeDay12", record::startTimeDay12)
        map(endTimeDay12).toPropertyWhenPresent("endTimeDay12", record::endTimeDay12)
        map(breakTimeDay12).toPropertyWhenPresent("breakTimeDay12", record::breakTimeDay12)
        map(workStyle13).toPropertyWhenPresent("workStyle13", record::workStyle13)
        map(startTimeDay13).toPropertyWhenPresent("startTimeDay13", record::startTimeDay13)
        map(endTimeDay13).toPropertyWhenPresent("endTimeDay13", record::endTimeDay13)
        map(breakTimeDay13).toPropertyWhenPresent("breakTimeDay13", record::breakTimeDay13)
        map(workStyle14).toPropertyWhenPresent("workStyle14", record::workStyle14)
        map(startTimeDay14).toPropertyWhenPresent("startTimeDay14", record::startTimeDay14)
        map(endTimeDay14).toPropertyWhenPresent("endTimeDay14", record::endTimeDay14)
        map(breakTimeDay14).toPropertyWhenPresent("breakTimeDay14", record::breakTimeDay14)
        map(workStyle15).toPropertyWhenPresent("workStyle15", record::workStyle15)
        map(startTimeDay15).toPropertyWhenPresent("startTimeDay15", record::startTimeDay15)
        map(endTimeDay15).toPropertyWhenPresent("endTimeDay15", record::endTimeDay15)
        map(breakTimeDay15).toPropertyWhenPresent("breakTimeDay15", record::breakTimeDay15)
        map(workStyle16).toPropertyWhenPresent("workStyle16", record::workStyle16)
        map(startTimeDay16).toPropertyWhenPresent("startTimeDay16", record::startTimeDay16)
        map(endTimeDay16).toPropertyWhenPresent("endTimeDay16", record::endTimeDay16)
        map(breakTimeDay16).toPropertyWhenPresent("breakTimeDay16", record::breakTimeDay16)
        map(workStyle17).toPropertyWhenPresent("workStyle17", record::workStyle17)
        map(startTimeDay17).toPropertyWhenPresent("startTimeDay17", record::startTimeDay17)
        map(endTimeDay17).toPropertyWhenPresent("endTimeDay17", record::endTimeDay17)
        map(breakTimeDay17).toPropertyWhenPresent("breakTimeDay17", record::breakTimeDay17)
        map(workStyle18).toPropertyWhenPresent("workStyle18", record::workStyle18)
        map(startTimeDay18).toPropertyWhenPresent("startTimeDay18", record::startTimeDay18)
        map(endTimeDay18).toPropertyWhenPresent("endTimeDay18", record::endTimeDay18)
        map(breakTimeDay18).toPropertyWhenPresent("breakTimeDay18", record::breakTimeDay18)
        map(workStyle19).toPropertyWhenPresent("workStyle19", record::workStyle19)
        map(startTimeDay19).toPropertyWhenPresent("startTimeDay19", record::startTimeDay19)
        map(endTimeDay19).toPropertyWhenPresent("endTimeDay19", record::endTimeDay19)
        map(breakTimeDay19).toPropertyWhenPresent("breakTimeDay19", record::breakTimeDay19)
        map(workStyle20).toPropertyWhenPresent("workStyle20", record::workStyle20)
        map(startTimeDay20).toPropertyWhenPresent("startTimeDay20", record::startTimeDay20)
        map(endTimeDay20).toPropertyWhenPresent("endTimeDay20", record::endTimeDay20)
        map(breakTimeDay20).toPropertyWhenPresent("breakTimeDay20", record::breakTimeDay20)
        map(workStyle21).toPropertyWhenPresent("workStyle21", record::workStyle21)
        map(startTimeDay21).toPropertyWhenPresent("startTimeDay21", record::startTimeDay21)
        map(endTimeDay21).toPropertyWhenPresent("endTimeDay21", record::endTimeDay21)
        map(breakTimeDay21).toPropertyWhenPresent("breakTimeDay21", record::breakTimeDay21)
        map(workStyle22).toPropertyWhenPresent("workStyle22", record::workStyle22)
        map(startTimeDay22).toPropertyWhenPresent("startTimeDay22", record::startTimeDay22)
        map(endTimeDay22).toPropertyWhenPresent("endTimeDay22", record::endTimeDay22)
        map(breakTimeDay22).toPropertyWhenPresent("breakTimeDay22", record::breakTimeDay22)
        map(workStyle23).toPropertyWhenPresent("workStyle23", record::workStyle23)
        map(startTimeDay23).toPropertyWhenPresent("startTimeDay23", record::startTimeDay23)
        map(endTimeDay23).toPropertyWhenPresent("endTimeDay23", record::endTimeDay23)
        map(breakTimeDay23).toPropertyWhenPresent("breakTimeDay23", record::breakTimeDay23)
        map(workStyle24).toPropertyWhenPresent("workStyle24", record::workStyle24)
        map(startTimeDay24).toPropertyWhenPresent("startTimeDay24", record::startTimeDay24)
        map(endTimeDay24).toPropertyWhenPresent("endTimeDay24", record::endTimeDay24)
        map(breakTimeDay24).toPropertyWhenPresent("breakTimeDay24", record::breakTimeDay24)
        map(workStyle25).toPropertyWhenPresent("workStyle25", record::workStyle25)
        map(startTimeDay25).toPropertyWhenPresent("startTimeDay25", record::startTimeDay25)
        map(endTimeDay25).toPropertyWhenPresent("endTimeDay25", record::endTimeDay25)
        map(breakTimeDay25).toPropertyWhenPresent("breakTimeDay25", record::breakTimeDay25)
        map(workStyle26).toPropertyWhenPresent("workStyle26", record::workStyle26)
        map(startTimeDay26).toPropertyWhenPresent("startTimeDay26", record::startTimeDay26)
        map(endTimeDay26).toPropertyWhenPresent("endTimeDay26", record::endTimeDay26)
        map(breakTimeDay26).toPropertyWhenPresent("breakTimeDay26", record::breakTimeDay26)
        map(workStyle27).toPropertyWhenPresent("workStyle27", record::workStyle27)
        map(startTimeDay27).toPropertyWhenPresent("startTimeDay27", record::startTimeDay27)
        map(endTimeDay27).toPropertyWhenPresent("endTimeDay27", record::endTimeDay27)
        map(breakTimeDay27).toPropertyWhenPresent("breakTimeDay27", record::breakTimeDay27)
        map(workStyle28).toPropertyWhenPresent("workStyle28", record::workStyle28)
        map(startTimeDay28).toPropertyWhenPresent("startTimeDay28", record::startTimeDay28)
        map(endTimeDay28).toPropertyWhenPresent("endTimeDay28", record::endTimeDay28)
        map(breakTimeDay28).toPropertyWhenPresent("breakTimeDay28", record::breakTimeDay28)
        map(workStyle29).toPropertyWhenPresent("workStyle29", record::workStyle29)
        map(startTimeDay29).toPropertyWhenPresent("startTimeDay29", record::startTimeDay29)
        map(endTimeDay29).toPropertyWhenPresent("endTimeDay29", record::endTimeDay29)
        map(breakTimeDay29).toPropertyWhenPresent("breakTimeDay29", record::breakTimeDay29)
        map(workStyle30).toPropertyWhenPresent("workStyle30", record::workStyle30)
        map(startTimeDay30).toPropertyWhenPresent("startTimeDay30", record::startTimeDay30)
        map(endTimeDay30).toPropertyWhenPresent("endTimeDay30", record::endTimeDay30)
        map(breakTimeDay30).toPropertyWhenPresent("breakTimeDay30", record::breakTimeDay30)
        map(workStyle31).toPropertyWhenPresent("workStyle31", record::workStyle31)
        map(startTimeDay31).toPropertyWhenPresent("startTimeDay31", record::startTimeDay31)
        map(endTimeDay31).toPropertyWhenPresent("endTimeDay31", record::endTimeDay31)
        map(breakTimeDay31).toPropertyWhenPresent("breakTimeDay31", record::breakTimeDay31)
    }

private val columnList = listOf(attendaceId, userId, year, month, workStyle1, startTimeDay1, endTimeDay1, breakTimeDay1, workStyle2, startTimeDay2, endTimeDay2, breakTimeDay2, workStyle3, startTimeDay3, endTimeDay3, breakTimeDay3, workStyle4, startTimeDay4, endTimeDay4, breakTimeDay4, workStyle5, startTimeDay5, endTimeDay5, breakTimeDay5, workStyle6, startTimeDay6, endTimeDay6, breakTimeDay6, workStyle7, startTimeDay7, endTimeDay7, breakTimeDay7, workStyle8, startTimeDay8, endTimeDay8, breakTimeDay8, workStyle9, startTimeDay9, endTimeDay9, breakTimeDay9, workStyle10, startTimeDay10, endTimeDay10, breakTimeDay10, workStyle11, startTimeDay11, endTimeDay11, breakTimeDay11, workStyle12, startTimeDay12, endTimeDay12, breakTimeDay12, workStyle13, startTimeDay13, endTimeDay13, breakTimeDay13, workStyle14, startTimeDay14, endTimeDay14, breakTimeDay14, workStyle15, startTimeDay15, endTimeDay15, breakTimeDay15, workStyle16, startTimeDay16, endTimeDay16, breakTimeDay16, workStyle17, startTimeDay17, endTimeDay17, breakTimeDay17, workStyle18, startTimeDay18, endTimeDay18, breakTimeDay18, workStyle19, startTimeDay19, endTimeDay19, breakTimeDay19, workStyle20, startTimeDay20, endTimeDay20, breakTimeDay20, workStyle21, startTimeDay21, endTimeDay21, breakTimeDay21, workStyle22, startTimeDay22, endTimeDay22, breakTimeDay22, workStyle23, startTimeDay23, endTimeDay23, breakTimeDay23, workStyle24, startTimeDay24, endTimeDay24, breakTimeDay24, workStyle25, startTimeDay25, endTimeDay25, breakTimeDay25, workStyle26, startTimeDay26, endTimeDay26, breakTimeDay26, workStyle27, startTimeDay27, endTimeDay27, breakTimeDay27, workStyle28, startTimeDay28, endTimeDay28, breakTimeDay28, workStyle29, startTimeDay29, endTimeDay29, breakTimeDay29, workStyle30, startTimeDay30, endTimeDay30, breakTimeDay30, workStyle31, startTimeDay31, endTimeDay31, breakTimeDay31)

fun AttendanceBasicInfoMapper.selectOne(completer: SelectCompleter) =
    selectOne(this::selectOne, columnList, AttendanceBasicInfo, completer)

fun AttendanceBasicInfoMapper.select(completer: SelectCompleter) =
    selectList(this::selectMany, columnList, AttendanceBasicInfo, completer)

fun AttendanceBasicInfoMapper.selectDistinct(completer: SelectCompleter) =
    selectDistinct(this::selectMany, columnList, AttendanceBasicInfo, completer)

fun AttendanceBasicInfoMapper.selectByPrimaryKey(attendaceId_: Int) =
    selectOne {
        where(attendaceId, isEqualTo(attendaceId_))
    }

fun AttendanceBasicInfoMapper.update(completer: UpdateCompleter) =
    update(this::update, AttendanceBasicInfo, completer)

fun KotlinUpdateBuilder.updateAllColumns(record: AttendanceBasicInfoRecord) =
    apply {
        set(attendaceId).equalTo(record::attendaceId)
        set(userId).equalTo(record::userId)
        set(year).equalTo(record::year)
        set(month).equalTo(record::month)
        set(workStyle1).equalTo(record::workStyle1)
        set(startTimeDay1).equalTo(record::startTimeDay1)
        set(endTimeDay1).equalTo(record::endTimeDay1)
        set(breakTimeDay1).equalTo(record::breakTimeDay1)
        set(workStyle2).equalTo(record::workStyle2)
        set(startTimeDay2).equalTo(record::startTimeDay2)
        set(endTimeDay2).equalTo(record::endTimeDay2)
        set(breakTimeDay2).equalTo(record::breakTimeDay2)
        set(workStyle3).equalTo(record::workStyle3)
        set(startTimeDay3).equalTo(record::startTimeDay3)
        set(endTimeDay3).equalTo(record::endTimeDay3)
        set(breakTimeDay3).equalTo(record::breakTimeDay3)
        set(workStyle4).equalTo(record::workStyle4)
        set(startTimeDay4).equalTo(record::startTimeDay4)
        set(endTimeDay4).equalTo(record::endTimeDay4)
        set(breakTimeDay4).equalTo(record::breakTimeDay4)
        set(workStyle5).equalTo(record::workStyle5)
        set(startTimeDay5).equalTo(record::startTimeDay5)
        set(endTimeDay5).equalTo(record::endTimeDay5)
        set(breakTimeDay5).equalTo(record::breakTimeDay5)
        set(workStyle6).equalTo(record::workStyle6)
        set(startTimeDay6).equalTo(record::startTimeDay6)
        set(endTimeDay6).equalTo(record::endTimeDay6)
        set(breakTimeDay6).equalTo(record::breakTimeDay6)
        set(workStyle7).equalTo(record::workStyle7)
        set(startTimeDay7).equalTo(record::startTimeDay7)
        set(endTimeDay7).equalTo(record::endTimeDay7)
        set(breakTimeDay7).equalTo(record::breakTimeDay7)
        set(workStyle8).equalTo(record::workStyle8)
        set(startTimeDay8).equalTo(record::startTimeDay8)
        set(endTimeDay8).equalTo(record::endTimeDay8)
        set(breakTimeDay8).equalTo(record::breakTimeDay8)
        set(workStyle9).equalTo(record::workStyle9)
        set(startTimeDay9).equalTo(record::startTimeDay9)
        set(endTimeDay9).equalTo(record::endTimeDay9)
        set(breakTimeDay9).equalTo(record::breakTimeDay9)
        set(workStyle10).equalTo(record::workStyle10)
        set(startTimeDay10).equalTo(record::startTimeDay10)
        set(endTimeDay10).equalTo(record::endTimeDay10)
        set(breakTimeDay10).equalTo(record::breakTimeDay10)
        set(workStyle11).equalTo(record::workStyle11)
        set(startTimeDay11).equalTo(record::startTimeDay11)
        set(endTimeDay11).equalTo(record::endTimeDay11)
        set(breakTimeDay11).equalTo(record::breakTimeDay11)
        set(workStyle12).equalTo(record::workStyle12)
        set(startTimeDay12).equalTo(record::startTimeDay12)
        set(endTimeDay12).equalTo(record::endTimeDay12)
        set(breakTimeDay12).equalTo(record::breakTimeDay12)
        set(workStyle13).equalTo(record::workStyle13)
        set(startTimeDay13).equalTo(record::startTimeDay13)
        set(endTimeDay13).equalTo(record::endTimeDay13)
        set(breakTimeDay13).equalTo(record::breakTimeDay13)
        set(workStyle14).equalTo(record::workStyle14)
        set(startTimeDay14).equalTo(record::startTimeDay14)
        set(endTimeDay14).equalTo(record::endTimeDay14)
        set(breakTimeDay14).equalTo(record::breakTimeDay14)
        set(workStyle15).equalTo(record::workStyle15)
        set(startTimeDay15).equalTo(record::startTimeDay15)
        set(endTimeDay15).equalTo(record::endTimeDay15)
        set(breakTimeDay15).equalTo(record::breakTimeDay15)
        set(workStyle16).equalTo(record::workStyle16)
        set(startTimeDay16).equalTo(record::startTimeDay16)
        set(endTimeDay16).equalTo(record::endTimeDay16)
        set(breakTimeDay16).equalTo(record::breakTimeDay16)
        set(workStyle17).equalTo(record::workStyle17)
        set(startTimeDay17).equalTo(record::startTimeDay17)
        set(endTimeDay17).equalTo(record::endTimeDay17)
        set(breakTimeDay17).equalTo(record::breakTimeDay17)
        set(workStyle18).equalTo(record::workStyle18)
        set(startTimeDay18).equalTo(record::startTimeDay18)
        set(endTimeDay18).equalTo(record::endTimeDay18)
        set(breakTimeDay18).equalTo(record::breakTimeDay18)
        set(workStyle19).equalTo(record::workStyle19)
        set(startTimeDay19).equalTo(record::startTimeDay19)
        set(endTimeDay19).equalTo(record::endTimeDay19)
        set(breakTimeDay19).equalTo(record::breakTimeDay19)
        set(workStyle20).equalTo(record::workStyle20)
        set(startTimeDay20).equalTo(record::startTimeDay20)
        set(endTimeDay20).equalTo(record::endTimeDay20)
        set(breakTimeDay20).equalTo(record::breakTimeDay20)
        set(workStyle21).equalTo(record::workStyle21)
        set(startTimeDay21).equalTo(record::startTimeDay21)
        set(endTimeDay21).equalTo(record::endTimeDay21)
        set(breakTimeDay21).equalTo(record::breakTimeDay21)
        set(workStyle22).equalTo(record::workStyle22)
        set(startTimeDay22).equalTo(record::startTimeDay22)
        set(endTimeDay22).equalTo(record::endTimeDay22)
        set(breakTimeDay22).equalTo(record::breakTimeDay22)
        set(workStyle23).equalTo(record::workStyle23)
        set(startTimeDay23).equalTo(record::startTimeDay23)
        set(endTimeDay23).equalTo(record::endTimeDay23)
        set(breakTimeDay23).equalTo(record::breakTimeDay23)
        set(workStyle24).equalTo(record::workStyle24)
        set(startTimeDay24).equalTo(record::startTimeDay24)
        set(endTimeDay24).equalTo(record::endTimeDay24)
        set(breakTimeDay24).equalTo(record::breakTimeDay24)
        set(workStyle25).equalTo(record::workStyle25)
        set(startTimeDay25).equalTo(record::startTimeDay25)
        set(endTimeDay25).equalTo(record::endTimeDay25)
        set(breakTimeDay25).equalTo(record::breakTimeDay25)
        set(workStyle26).equalTo(record::workStyle26)
        set(startTimeDay26).equalTo(record::startTimeDay26)
        set(endTimeDay26).equalTo(record::endTimeDay26)
        set(breakTimeDay26).equalTo(record::breakTimeDay26)
        set(workStyle27).equalTo(record::workStyle27)
        set(startTimeDay27).equalTo(record::startTimeDay27)
        set(endTimeDay27).equalTo(record::endTimeDay27)
        set(breakTimeDay27).equalTo(record::breakTimeDay27)
        set(workStyle28).equalTo(record::workStyle28)
        set(startTimeDay28).equalTo(record::startTimeDay28)
        set(endTimeDay28).equalTo(record::endTimeDay28)
        set(breakTimeDay28).equalTo(record::breakTimeDay28)
        set(workStyle29).equalTo(record::workStyle29)
        set(startTimeDay29).equalTo(record::startTimeDay29)
        set(endTimeDay29).equalTo(record::endTimeDay29)
        set(breakTimeDay29).equalTo(record::breakTimeDay29)
        set(workStyle30).equalTo(record::workStyle30)
        set(startTimeDay30).equalTo(record::startTimeDay30)
        set(endTimeDay30).equalTo(record::endTimeDay30)
        set(breakTimeDay30).equalTo(record::breakTimeDay30)
        set(workStyle31).equalTo(record::workStyle31)
        set(startTimeDay31).equalTo(record::startTimeDay31)
        set(endTimeDay31).equalTo(record::endTimeDay31)
        set(breakTimeDay31).equalTo(record::breakTimeDay31)
    }

fun KotlinUpdateBuilder.updateSelectiveColumns(record: AttendanceBasicInfoRecord) =
    apply {
        set(attendaceId).equalToWhenPresent(record::attendaceId)
        set(userId).equalToWhenPresent(record::userId)
        set(year).equalToWhenPresent(record::year)
        set(month).equalToWhenPresent(record::month)
        set(workStyle1).equalToWhenPresent(record::workStyle1)
        set(startTimeDay1).equalToWhenPresent(record::startTimeDay1)
        set(endTimeDay1).equalToWhenPresent(record::endTimeDay1)
        set(breakTimeDay1).equalToWhenPresent(record::breakTimeDay1)
        set(workStyle2).equalToWhenPresent(record::workStyle2)
        set(startTimeDay2).equalToWhenPresent(record::startTimeDay2)
        set(endTimeDay2).equalToWhenPresent(record::endTimeDay2)
        set(breakTimeDay2).equalToWhenPresent(record::breakTimeDay2)
        set(workStyle3).equalToWhenPresent(record::workStyle3)
        set(startTimeDay3).equalToWhenPresent(record::startTimeDay3)
        set(endTimeDay3).equalToWhenPresent(record::endTimeDay3)
        set(breakTimeDay3).equalToWhenPresent(record::breakTimeDay3)
        set(workStyle4).equalToWhenPresent(record::workStyle4)
        set(startTimeDay4).equalToWhenPresent(record::startTimeDay4)
        set(endTimeDay4).equalToWhenPresent(record::endTimeDay4)
        set(breakTimeDay4).equalToWhenPresent(record::breakTimeDay4)
        set(workStyle5).equalToWhenPresent(record::workStyle5)
        set(startTimeDay5).equalToWhenPresent(record::startTimeDay5)
        set(endTimeDay5).equalToWhenPresent(record::endTimeDay5)
        set(breakTimeDay5).equalToWhenPresent(record::breakTimeDay5)
        set(workStyle6).equalToWhenPresent(record::workStyle6)
        set(startTimeDay6).equalToWhenPresent(record::startTimeDay6)
        set(endTimeDay6).equalToWhenPresent(record::endTimeDay6)
        set(breakTimeDay6).equalToWhenPresent(record::breakTimeDay6)
        set(workStyle7).equalToWhenPresent(record::workStyle7)
        set(startTimeDay7).equalToWhenPresent(record::startTimeDay7)
        set(endTimeDay7).equalToWhenPresent(record::endTimeDay7)
        set(breakTimeDay7).equalToWhenPresent(record::breakTimeDay7)
        set(workStyle8).equalToWhenPresent(record::workStyle8)
        set(startTimeDay8).equalToWhenPresent(record::startTimeDay8)
        set(endTimeDay8).equalToWhenPresent(record::endTimeDay8)
        set(breakTimeDay8).equalToWhenPresent(record::breakTimeDay8)
        set(workStyle9).equalToWhenPresent(record::workStyle9)
        set(startTimeDay9).equalToWhenPresent(record::startTimeDay9)
        set(endTimeDay9).equalToWhenPresent(record::endTimeDay9)
        set(breakTimeDay9).equalToWhenPresent(record::breakTimeDay9)
        set(workStyle10).equalToWhenPresent(record::workStyle10)
        set(startTimeDay10).equalToWhenPresent(record::startTimeDay10)
        set(endTimeDay10).equalToWhenPresent(record::endTimeDay10)
        set(breakTimeDay10).equalToWhenPresent(record::breakTimeDay10)
        set(workStyle11).equalToWhenPresent(record::workStyle11)
        set(startTimeDay11).equalToWhenPresent(record::startTimeDay11)
        set(endTimeDay11).equalToWhenPresent(record::endTimeDay11)
        set(breakTimeDay11).equalToWhenPresent(record::breakTimeDay11)
        set(workStyle12).equalToWhenPresent(record::workStyle12)
        set(startTimeDay12).equalToWhenPresent(record::startTimeDay12)
        set(endTimeDay12).equalToWhenPresent(record::endTimeDay12)
        set(breakTimeDay12).equalToWhenPresent(record::breakTimeDay12)
        set(workStyle13).equalToWhenPresent(record::workStyle13)
        set(startTimeDay13).equalToWhenPresent(record::startTimeDay13)
        set(endTimeDay13).equalToWhenPresent(record::endTimeDay13)
        set(breakTimeDay13).equalToWhenPresent(record::breakTimeDay13)
        set(workStyle14).equalToWhenPresent(record::workStyle14)
        set(startTimeDay14).equalToWhenPresent(record::startTimeDay14)
        set(endTimeDay14).equalToWhenPresent(record::endTimeDay14)
        set(breakTimeDay14).equalToWhenPresent(record::breakTimeDay14)
        set(workStyle15).equalToWhenPresent(record::workStyle15)
        set(startTimeDay15).equalToWhenPresent(record::startTimeDay15)
        set(endTimeDay15).equalToWhenPresent(record::endTimeDay15)
        set(breakTimeDay15).equalToWhenPresent(record::breakTimeDay15)
        set(workStyle16).equalToWhenPresent(record::workStyle16)
        set(startTimeDay16).equalToWhenPresent(record::startTimeDay16)
        set(endTimeDay16).equalToWhenPresent(record::endTimeDay16)
        set(breakTimeDay16).equalToWhenPresent(record::breakTimeDay16)
        set(workStyle17).equalToWhenPresent(record::workStyle17)
        set(startTimeDay17).equalToWhenPresent(record::startTimeDay17)
        set(endTimeDay17).equalToWhenPresent(record::endTimeDay17)
        set(breakTimeDay17).equalToWhenPresent(record::breakTimeDay17)
        set(workStyle18).equalToWhenPresent(record::workStyle18)
        set(startTimeDay18).equalToWhenPresent(record::startTimeDay18)
        set(endTimeDay18).equalToWhenPresent(record::endTimeDay18)
        set(breakTimeDay18).equalToWhenPresent(record::breakTimeDay18)
        set(workStyle19).equalToWhenPresent(record::workStyle19)
        set(startTimeDay19).equalToWhenPresent(record::startTimeDay19)
        set(endTimeDay19).equalToWhenPresent(record::endTimeDay19)
        set(breakTimeDay19).equalToWhenPresent(record::breakTimeDay19)
        set(workStyle20).equalToWhenPresent(record::workStyle20)
        set(startTimeDay20).equalToWhenPresent(record::startTimeDay20)
        set(endTimeDay20).equalToWhenPresent(record::endTimeDay20)
        set(breakTimeDay20).equalToWhenPresent(record::breakTimeDay20)
        set(workStyle21).equalToWhenPresent(record::workStyle21)
        set(startTimeDay21).equalToWhenPresent(record::startTimeDay21)
        set(endTimeDay21).equalToWhenPresent(record::endTimeDay21)
        set(breakTimeDay21).equalToWhenPresent(record::breakTimeDay21)
        set(workStyle22).equalToWhenPresent(record::workStyle22)
        set(startTimeDay22).equalToWhenPresent(record::startTimeDay22)
        set(endTimeDay22).equalToWhenPresent(record::endTimeDay22)
        set(breakTimeDay22).equalToWhenPresent(record::breakTimeDay22)
        set(workStyle23).equalToWhenPresent(record::workStyle23)
        set(startTimeDay23).equalToWhenPresent(record::startTimeDay23)
        set(endTimeDay23).equalToWhenPresent(record::endTimeDay23)
        set(breakTimeDay23).equalToWhenPresent(record::breakTimeDay23)
        set(workStyle24).equalToWhenPresent(record::workStyle24)
        set(startTimeDay24).equalToWhenPresent(record::startTimeDay24)
        set(endTimeDay24).equalToWhenPresent(record::endTimeDay24)
        set(breakTimeDay24).equalToWhenPresent(record::breakTimeDay24)
        set(workStyle25).equalToWhenPresent(record::workStyle25)
        set(startTimeDay25).equalToWhenPresent(record::startTimeDay25)
        set(endTimeDay25).equalToWhenPresent(record::endTimeDay25)
        set(breakTimeDay25).equalToWhenPresent(record::breakTimeDay25)
        set(workStyle26).equalToWhenPresent(record::workStyle26)
        set(startTimeDay26).equalToWhenPresent(record::startTimeDay26)
        set(endTimeDay26).equalToWhenPresent(record::endTimeDay26)
        set(breakTimeDay26).equalToWhenPresent(record::breakTimeDay26)
        set(workStyle27).equalToWhenPresent(record::workStyle27)
        set(startTimeDay27).equalToWhenPresent(record::startTimeDay27)
        set(endTimeDay27).equalToWhenPresent(record::endTimeDay27)
        set(breakTimeDay27).equalToWhenPresent(record::breakTimeDay27)
        set(workStyle28).equalToWhenPresent(record::workStyle28)
        set(startTimeDay28).equalToWhenPresent(record::startTimeDay28)
        set(endTimeDay28).equalToWhenPresent(record::endTimeDay28)
        set(breakTimeDay28).equalToWhenPresent(record::breakTimeDay28)
        set(workStyle29).equalToWhenPresent(record::workStyle29)
        set(startTimeDay29).equalToWhenPresent(record::startTimeDay29)
        set(endTimeDay29).equalToWhenPresent(record::endTimeDay29)
        set(breakTimeDay29).equalToWhenPresent(record::breakTimeDay29)
        set(workStyle30).equalToWhenPresent(record::workStyle30)
        set(startTimeDay30).equalToWhenPresent(record::startTimeDay30)
        set(endTimeDay30).equalToWhenPresent(record::endTimeDay30)
        set(breakTimeDay30).equalToWhenPresent(record::breakTimeDay30)
        set(workStyle31).equalToWhenPresent(record::workStyle31)
        set(startTimeDay31).equalToWhenPresent(record::startTimeDay31)
        set(endTimeDay31).equalToWhenPresent(record::endTimeDay31)
        set(breakTimeDay31).equalToWhenPresent(record::breakTimeDay31)
    }

fun AttendanceBasicInfoMapper.updateByPrimaryKey(record: AttendanceBasicInfoRecord) =
    update {
        set(userId).equalTo(record::userId)
        set(year).equalTo(record::year)
        set(month).equalTo(record::month)
        set(workStyle1).equalTo(record::workStyle1)
        set(startTimeDay1).equalTo(record::startTimeDay1)
        set(endTimeDay1).equalTo(record::endTimeDay1)
        set(breakTimeDay1).equalTo(record::breakTimeDay1)
        set(workStyle2).equalTo(record::workStyle2)
        set(startTimeDay2).equalTo(record::startTimeDay2)
        set(endTimeDay2).equalTo(record::endTimeDay2)
        set(breakTimeDay2).equalTo(record::breakTimeDay2)
        set(workStyle3).equalTo(record::workStyle3)
        set(startTimeDay3).equalTo(record::startTimeDay3)
        set(endTimeDay3).equalTo(record::endTimeDay3)
        set(breakTimeDay3).equalTo(record::breakTimeDay3)
        set(workStyle4).equalTo(record::workStyle4)
        set(startTimeDay4).equalTo(record::startTimeDay4)
        set(endTimeDay4).equalTo(record::endTimeDay4)
        set(breakTimeDay4).equalTo(record::breakTimeDay4)
        set(workStyle5).equalTo(record::workStyle5)
        set(startTimeDay5).equalTo(record::startTimeDay5)
        set(endTimeDay5).equalTo(record::endTimeDay5)
        set(breakTimeDay5).equalTo(record::breakTimeDay5)
        set(workStyle6).equalTo(record::workStyle6)
        set(startTimeDay6).equalTo(record::startTimeDay6)
        set(endTimeDay6).equalTo(record::endTimeDay6)
        set(breakTimeDay6).equalTo(record::breakTimeDay6)
        set(workStyle7).equalTo(record::workStyle7)
        set(startTimeDay7).equalTo(record::startTimeDay7)
        set(endTimeDay7).equalTo(record::endTimeDay7)
        set(breakTimeDay7).equalTo(record::breakTimeDay7)
        set(workStyle8).equalTo(record::workStyle8)
        set(startTimeDay8).equalTo(record::startTimeDay8)
        set(endTimeDay8).equalTo(record::endTimeDay8)
        set(breakTimeDay8).equalTo(record::breakTimeDay8)
        set(workStyle9).equalTo(record::workStyle9)
        set(startTimeDay9).equalTo(record::startTimeDay9)
        set(endTimeDay9).equalTo(record::endTimeDay9)
        set(breakTimeDay9).equalTo(record::breakTimeDay9)
        set(workStyle10).equalTo(record::workStyle10)
        set(startTimeDay10).equalTo(record::startTimeDay10)
        set(endTimeDay10).equalTo(record::endTimeDay10)
        set(breakTimeDay10).equalTo(record::breakTimeDay10)
        set(workStyle11).equalTo(record::workStyle11)
        set(startTimeDay11).equalTo(record::startTimeDay11)
        set(endTimeDay11).equalTo(record::endTimeDay11)
        set(breakTimeDay11).equalTo(record::breakTimeDay11)
        set(workStyle12).equalTo(record::workStyle12)
        set(startTimeDay12).equalTo(record::startTimeDay12)
        set(endTimeDay12).equalTo(record::endTimeDay12)
        set(breakTimeDay12).equalTo(record::breakTimeDay12)
        set(workStyle13).equalTo(record::workStyle13)
        set(startTimeDay13).equalTo(record::startTimeDay13)
        set(endTimeDay13).equalTo(record::endTimeDay13)
        set(breakTimeDay13).equalTo(record::breakTimeDay13)
        set(workStyle14).equalTo(record::workStyle14)
        set(startTimeDay14).equalTo(record::startTimeDay14)
        set(endTimeDay14).equalTo(record::endTimeDay14)
        set(breakTimeDay14).equalTo(record::breakTimeDay14)
        set(workStyle15).equalTo(record::workStyle15)
        set(startTimeDay15).equalTo(record::startTimeDay15)
        set(endTimeDay15).equalTo(record::endTimeDay15)
        set(breakTimeDay15).equalTo(record::breakTimeDay15)
        set(workStyle16).equalTo(record::workStyle16)
        set(startTimeDay16).equalTo(record::startTimeDay16)
        set(endTimeDay16).equalTo(record::endTimeDay16)
        set(breakTimeDay16).equalTo(record::breakTimeDay16)
        set(workStyle17).equalTo(record::workStyle17)
        set(startTimeDay17).equalTo(record::startTimeDay17)
        set(endTimeDay17).equalTo(record::endTimeDay17)
        set(breakTimeDay17).equalTo(record::breakTimeDay17)
        set(workStyle18).equalTo(record::workStyle18)
        set(startTimeDay18).equalTo(record::startTimeDay18)
        set(endTimeDay18).equalTo(record::endTimeDay18)
        set(breakTimeDay18).equalTo(record::breakTimeDay18)
        set(workStyle19).equalTo(record::workStyle19)
        set(startTimeDay19).equalTo(record::startTimeDay19)
        set(endTimeDay19).equalTo(record::endTimeDay19)
        set(breakTimeDay19).equalTo(record::breakTimeDay19)
        set(workStyle20).equalTo(record::workStyle20)
        set(startTimeDay20).equalTo(record::startTimeDay20)
        set(endTimeDay20).equalTo(record::endTimeDay20)
        set(breakTimeDay20).equalTo(record::breakTimeDay20)
        set(workStyle21).equalTo(record::workStyle21)
        set(startTimeDay21).equalTo(record::startTimeDay21)
        set(endTimeDay21).equalTo(record::endTimeDay21)
        set(breakTimeDay21).equalTo(record::breakTimeDay21)
        set(workStyle22).equalTo(record::workStyle22)
        set(startTimeDay22).equalTo(record::startTimeDay22)
        set(endTimeDay22).equalTo(record::endTimeDay22)
        set(breakTimeDay22).equalTo(record::breakTimeDay22)
        set(workStyle23).equalTo(record::workStyle23)
        set(startTimeDay23).equalTo(record::startTimeDay23)
        set(endTimeDay23).equalTo(record::endTimeDay23)
        set(breakTimeDay23).equalTo(record::breakTimeDay23)
        set(workStyle24).equalTo(record::workStyle24)
        set(startTimeDay24).equalTo(record::startTimeDay24)
        set(endTimeDay24).equalTo(record::endTimeDay24)
        set(breakTimeDay24).equalTo(record::breakTimeDay24)
        set(workStyle25).equalTo(record::workStyle25)
        set(startTimeDay25).equalTo(record::startTimeDay25)
        set(endTimeDay25).equalTo(record::endTimeDay25)
        set(breakTimeDay25).equalTo(record::breakTimeDay25)
        set(workStyle26).equalTo(record::workStyle26)
        set(startTimeDay26).equalTo(record::startTimeDay26)
        set(endTimeDay26).equalTo(record::endTimeDay26)
        set(breakTimeDay26).equalTo(record::breakTimeDay26)
        set(workStyle27).equalTo(record::workStyle27)
        set(startTimeDay27).equalTo(record::startTimeDay27)
        set(endTimeDay27).equalTo(record::endTimeDay27)
        set(breakTimeDay27).equalTo(record::breakTimeDay27)
        set(workStyle28).equalTo(record::workStyle28)
        set(startTimeDay28).equalTo(record::startTimeDay28)
        set(endTimeDay28).equalTo(record::endTimeDay28)
        set(breakTimeDay28).equalTo(record::breakTimeDay28)
        set(workStyle29).equalTo(record::workStyle29)
        set(startTimeDay29).equalTo(record::startTimeDay29)
        set(endTimeDay29).equalTo(record::endTimeDay29)
        set(breakTimeDay29).equalTo(record::breakTimeDay29)
        set(workStyle30).equalTo(record::workStyle30)
        set(startTimeDay30).equalTo(record::startTimeDay30)
        set(endTimeDay30).equalTo(record::endTimeDay30)
        set(breakTimeDay30).equalTo(record::breakTimeDay30)
        set(workStyle31).equalTo(record::workStyle31)
        set(startTimeDay31).equalTo(record::startTimeDay31)
        set(endTimeDay31).equalTo(record::endTimeDay31)
        set(breakTimeDay31).equalTo(record::breakTimeDay31)
        where(attendaceId, isEqualTo(record::attendaceId))
    }

fun AttendanceBasicInfoMapper.updateByPrimaryKeySelective(record: AttendanceBasicInfoRecord) =
    update {
        set(userId).equalToWhenPresent(record::userId)
        set(year).equalToWhenPresent(record::year)
        set(month).equalToWhenPresent(record::month)
        set(workStyle1).equalToWhenPresent(record::workStyle1)
        set(startTimeDay1).equalToWhenPresent(record::startTimeDay1)
        set(endTimeDay1).equalToWhenPresent(record::endTimeDay1)
        set(breakTimeDay1).equalToWhenPresent(record::breakTimeDay1)
        set(workStyle2).equalToWhenPresent(record::workStyle2)
        set(startTimeDay2).equalToWhenPresent(record::startTimeDay2)
        set(endTimeDay2).equalToWhenPresent(record::endTimeDay2)
        set(breakTimeDay2).equalToWhenPresent(record::breakTimeDay2)
        set(workStyle3).equalToWhenPresent(record::workStyle3)
        set(startTimeDay3).equalToWhenPresent(record::startTimeDay3)
        set(endTimeDay3).equalToWhenPresent(record::endTimeDay3)
        set(breakTimeDay3).equalToWhenPresent(record::breakTimeDay3)
        set(workStyle4).equalToWhenPresent(record::workStyle4)
        set(startTimeDay4).equalToWhenPresent(record::startTimeDay4)
        set(endTimeDay4).equalToWhenPresent(record::endTimeDay4)
        set(breakTimeDay4).equalToWhenPresent(record::breakTimeDay4)
        set(workStyle5).equalToWhenPresent(record::workStyle5)
        set(startTimeDay5).equalToWhenPresent(record::startTimeDay5)
        set(endTimeDay5).equalToWhenPresent(record::endTimeDay5)
        set(breakTimeDay5).equalToWhenPresent(record::breakTimeDay5)
        set(workStyle6).equalToWhenPresent(record::workStyle6)
        set(startTimeDay6).equalToWhenPresent(record::startTimeDay6)
        set(endTimeDay6).equalToWhenPresent(record::endTimeDay6)
        set(breakTimeDay6).equalToWhenPresent(record::breakTimeDay6)
        set(workStyle7).equalToWhenPresent(record::workStyle7)
        set(startTimeDay7).equalToWhenPresent(record::startTimeDay7)
        set(endTimeDay7).equalToWhenPresent(record::endTimeDay7)
        set(breakTimeDay7).equalToWhenPresent(record::breakTimeDay7)
        set(workStyle8).equalToWhenPresent(record::workStyle8)
        set(startTimeDay8).equalToWhenPresent(record::startTimeDay8)
        set(endTimeDay8).equalToWhenPresent(record::endTimeDay8)
        set(breakTimeDay8).equalToWhenPresent(record::breakTimeDay8)
        set(workStyle9).equalToWhenPresent(record::workStyle9)
        set(startTimeDay9).equalToWhenPresent(record::startTimeDay9)
        set(endTimeDay9).equalToWhenPresent(record::endTimeDay9)
        set(breakTimeDay9).equalToWhenPresent(record::breakTimeDay9)
        set(workStyle10).equalToWhenPresent(record::workStyle10)
        set(startTimeDay10).equalToWhenPresent(record::startTimeDay10)
        set(endTimeDay10).equalToWhenPresent(record::endTimeDay10)
        set(breakTimeDay10).equalToWhenPresent(record::breakTimeDay10)
        set(workStyle11).equalToWhenPresent(record::workStyle11)
        set(startTimeDay11).equalToWhenPresent(record::startTimeDay11)
        set(endTimeDay11).equalToWhenPresent(record::endTimeDay11)
        set(breakTimeDay11).equalToWhenPresent(record::breakTimeDay11)
        set(workStyle12).equalToWhenPresent(record::workStyle12)
        set(startTimeDay12).equalToWhenPresent(record::startTimeDay12)
        set(endTimeDay12).equalToWhenPresent(record::endTimeDay12)
        set(breakTimeDay12).equalToWhenPresent(record::breakTimeDay12)
        set(workStyle13).equalToWhenPresent(record::workStyle13)
        set(startTimeDay13).equalToWhenPresent(record::startTimeDay13)
        set(endTimeDay13).equalToWhenPresent(record::endTimeDay13)
        set(breakTimeDay13).equalToWhenPresent(record::breakTimeDay13)
        set(workStyle14).equalToWhenPresent(record::workStyle14)
        set(startTimeDay14).equalToWhenPresent(record::startTimeDay14)
        set(endTimeDay14).equalToWhenPresent(record::endTimeDay14)
        set(breakTimeDay14).equalToWhenPresent(record::breakTimeDay14)
        set(workStyle15).equalToWhenPresent(record::workStyle15)
        set(startTimeDay15).equalToWhenPresent(record::startTimeDay15)
        set(endTimeDay15).equalToWhenPresent(record::endTimeDay15)
        set(breakTimeDay15).equalToWhenPresent(record::breakTimeDay15)
        set(workStyle16).equalToWhenPresent(record::workStyle16)
        set(startTimeDay16).equalToWhenPresent(record::startTimeDay16)
        set(endTimeDay16).equalToWhenPresent(record::endTimeDay16)
        set(breakTimeDay16).equalToWhenPresent(record::breakTimeDay16)
        set(workStyle17).equalToWhenPresent(record::workStyle17)
        set(startTimeDay17).equalToWhenPresent(record::startTimeDay17)
        set(endTimeDay17).equalToWhenPresent(record::endTimeDay17)
        set(breakTimeDay17).equalToWhenPresent(record::breakTimeDay17)
        set(workStyle18).equalToWhenPresent(record::workStyle18)
        set(startTimeDay18).equalToWhenPresent(record::startTimeDay18)
        set(endTimeDay18).equalToWhenPresent(record::endTimeDay18)
        set(breakTimeDay18).equalToWhenPresent(record::breakTimeDay18)
        set(workStyle19).equalToWhenPresent(record::workStyle19)
        set(startTimeDay19).equalToWhenPresent(record::startTimeDay19)
        set(endTimeDay19).equalToWhenPresent(record::endTimeDay19)
        set(breakTimeDay19).equalToWhenPresent(record::breakTimeDay19)
        set(workStyle20).equalToWhenPresent(record::workStyle20)
        set(startTimeDay20).equalToWhenPresent(record::startTimeDay20)
        set(endTimeDay20).equalToWhenPresent(record::endTimeDay20)
        set(breakTimeDay20).equalToWhenPresent(record::breakTimeDay20)
        set(workStyle21).equalToWhenPresent(record::workStyle21)
        set(startTimeDay21).equalToWhenPresent(record::startTimeDay21)
        set(endTimeDay21).equalToWhenPresent(record::endTimeDay21)
        set(breakTimeDay21).equalToWhenPresent(record::breakTimeDay21)
        set(workStyle22).equalToWhenPresent(record::workStyle22)
        set(startTimeDay22).equalToWhenPresent(record::startTimeDay22)
        set(endTimeDay22).equalToWhenPresent(record::endTimeDay22)
        set(breakTimeDay22).equalToWhenPresent(record::breakTimeDay22)
        set(workStyle23).equalToWhenPresent(record::workStyle23)
        set(startTimeDay23).equalToWhenPresent(record::startTimeDay23)
        set(endTimeDay23).equalToWhenPresent(record::endTimeDay23)
        set(breakTimeDay23).equalToWhenPresent(record::breakTimeDay23)
        set(workStyle24).equalToWhenPresent(record::workStyle24)
        set(startTimeDay24).equalToWhenPresent(record::startTimeDay24)
        set(endTimeDay24).equalToWhenPresent(record::endTimeDay24)
        set(breakTimeDay24).equalToWhenPresent(record::breakTimeDay24)
        set(workStyle25).equalToWhenPresent(record::workStyle25)
        set(startTimeDay25).equalToWhenPresent(record::startTimeDay25)
        set(endTimeDay25).equalToWhenPresent(record::endTimeDay25)
        set(breakTimeDay25).equalToWhenPresent(record::breakTimeDay25)
        set(workStyle26).equalToWhenPresent(record::workStyle26)
        set(startTimeDay26).equalToWhenPresent(record::startTimeDay26)
        set(endTimeDay26).equalToWhenPresent(record::endTimeDay26)
        set(breakTimeDay26).equalToWhenPresent(record::breakTimeDay26)
        set(workStyle27).equalToWhenPresent(record::workStyle27)
        set(startTimeDay27).equalToWhenPresent(record::startTimeDay27)
        set(endTimeDay27).equalToWhenPresent(record::endTimeDay27)
        set(breakTimeDay27).equalToWhenPresent(record::breakTimeDay27)
        set(workStyle28).equalToWhenPresent(record::workStyle28)
        set(startTimeDay28).equalToWhenPresent(record::startTimeDay28)
        set(endTimeDay28).equalToWhenPresent(record::endTimeDay28)
        set(breakTimeDay28).equalToWhenPresent(record::breakTimeDay28)
        set(workStyle29).equalToWhenPresent(record::workStyle29)
        set(startTimeDay29).equalToWhenPresent(record::startTimeDay29)
        set(endTimeDay29).equalToWhenPresent(record::endTimeDay29)
        set(breakTimeDay29).equalToWhenPresent(record::breakTimeDay29)
        set(workStyle30).equalToWhenPresent(record::workStyle30)
        set(startTimeDay30).equalToWhenPresent(record::startTimeDay30)
        set(endTimeDay30).equalToWhenPresent(record::endTimeDay30)
        set(breakTimeDay30).equalToWhenPresent(record::breakTimeDay30)
        set(workStyle31).equalToWhenPresent(record::workStyle31)
        set(startTimeDay31).equalToWhenPresent(record::startTimeDay31)
        set(endTimeDay31).equalToWhenPresent(record::endTimeDay31)
        set(breakTimeDay31).equalToWhenPresent(record::breakTimeDay31)
        where(attendaceId, isEqualTo(record::attendaceId))
    }